#!/usr/bin/env sh

fn - h : \
  (yabai -m query --spaces --display \
  | jq -re '(.[] as $arr | .[] | select(.index == ($arr | select(."has-focus" == true).index - 1))."first-window") // (last | ."first-window")' \
  | xargs yabai -m window --focus) \
  && sketchybar --trigger window_focused
fn - j : \
  (yabai -m window --focus next || yabai -m window --focus first) \
  && sketchybar --trigger window_focused
fn - k : \
  (yabai -m window --focus stack.next || yabai -m window --focus stack.first) \
  && sketchybar --trigger window_focused
fn - l : \
  (yabai -m query --spaces --display \
  | jq -re '(.[] as $arr | .[] | select(.index == ($arr | select(."has-focus" == true).index + 1))."first-window") // (first | ."first-window")' \
  | xargs yabai -m window --focus) \
  && sketchybar --trigger window_focused

fn + cmd - h : yabai -m window --swap west
fn + cmd - j : yabai -m window --swap south
fn + cmd - k : yabai -m window --swap north
fn + cmd - l : yabai -m window --swap east

fn + alt - h : yabai -m window --warp west
fn + alt - j : yabai -m window --warp south
fn + alt - k : yabai -m window --warp north
fn + alt - l : yabai -m window --warp east

fn + ctrl - h : yabai -m window --stack west
fn + ctrl - j : yabai -m window --stack south
fn + ctrl - k : yabai -m window --stack north
fn + ctrl - l : yabai -m window --stack east

fn + shift - h : \
  yabai -m window --resize left:-20:0; \
  yabai -m window --resize right:-20:0
fn + shift - j : \
  yabai -m window --resize bottom:0:20; \
  yabai -m window --resize top:0:20
fn + shift - k : \
  yabai -m window --resize top:0:-20; \
  yabai -m window --resize bottom:0:-20
fn + shift - l : \
  yabai -m window --resize right:20:0; \
  yabai -m window --resize left:20:0

fn - q : yabai -m window --close
fn - s : yabai -m window --toggle split
fn - f : yabai -m query --windows --space \
  | jq -rec '.[].id' \
  | xargs -L 1 -I {} yabai -m window {} --toggle zoom-fullscreen

fn - n : yabai -m window --space next
fn - p : yabai -m window --space prev

fn - x : yabai -m space --mirror x-axis
fn - y : yabai -m space --mirror y-axis

fn - r : yabai -m space --rotate 270
fn + shift - r : yabai -m space --rotate 90

fn - b : yabai -m space --balance
fn - g : sh ~/.config/borders/sync-gaps.sh

fn + shift - f : yabai -m window --toggle native-fullscreen
fn + shift - q : \
  brew services restart sketchybar; \
  brew services restart borders; \
  yabai --restart-service; \
  skhd --restart-service

fn - o : open ~/
fn - t : open -a kitty
fn - d : open -a Discord
fn - m : open -a Spotify

fn + shift - o : open -n ~/
fn + shift - t : open -na kitty
fn + shift - c : open -na "Google Chrome"
fn + shift - d : open -na Discord
fn + shift - m : open -na Spotify

fn - space : sketchybar --bar hidden=toggle
fn + shift - space : sketchybar --exit
fn + ctrl - space : sketchybar --update

:: default : $HOME/.config/sketchybar/scripts/mode.sh normal
:: mode_chrome : open -a "Google Chrome"; $HOME/.config/sketchybar/scripts/mode.sh chrome

default < fn - c ; mode_chrome

mode_chrome < escape ; default
mode_chrome < fn - c ; default
mode_chrome < fn - j : skhd -k escape; skhd -k "fn - j"

# Better navigation.
mode_chrome < j : skhd -k "down"
mode_chrome < k : skhd -k "up"
mode_chrome < shift - j : skhd -k "cmd + alt - down"
mode_chrome < shift - k : skhd -k "cmd + alt - up"
# Jump to the next/previous open tab.
mode_chrome < l : skhd -k "ctrl - tab"
mode_chrome < h : skhd -k "ctrl + shift - tab"
# Move tabs right or left.
mode_chrome < shift - l : skhd -k "ctrl + shift - pagedown"
mode_chrome < shift - h : skhd -k "ctrl + shift - pageup"
