#!/usr/bin/env sh

yabai -m config layout                      bsp
yabai -m config auto_balance                off
yabai -m config window_border               on
yabai -m config window_border_radius        12
yabai -m config window_border_width         1
yabai -m config window_gap                  8
yabai -m config top_padding                 2
yabai -m config left_padding                2
yabai -m config right_padding               2
yabai -m config bottom_padding              2
yabai -m config active_window_border_color  0xFF40FF00
yabai -m config normal_window_border_color  0x00FFFFFF
yabai -m config insert_feedback_color       0xFFD75F5F

yabai -m config --space 2 split_ratio 0.6

yabai -m rule --add app="^Системные настройки$" sticky=on layer=above manage=off
yabai -m rule --add app="^Проводник$" sticky=on layer=above manage=off

# Must be at the end of the file
YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &
