#!/usr/bin/env sh

launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

yabai -m config layout                      bsp          \
                active_window_opacity       1.0          \
                normal_window_opacity       0.95         \
                window_animation_duration   0.2          \
                window_shadow               float        \
                window_opacity              on           \
                window_opacity_duration     0.15         \
                window_border               on           \
                window_border_hidpi         off          \
                window_border_width         2            \
                window_border_radius        11           \
                window_gap                  8            \
                external_bar                all:33:0     \
                top_padding                 10           \
                bottom_padding              10           \
                left_padding                10           \
                right_padding               10           \
                active_window_border_color  0xffe1e3e4   \
                normal_window_border_color  0xff2a2f38   \
                insert_feedback_color       0xff9dd274   \
                auto_balance                off          \
                split_ratio 0.5                          \
                --space 2 split_ratio 0.6

yabai -m rule --add app="^(Системные настройки|Finder|App Store)$" layer=above manage=off
yabai -m rule --add app="^(iTerm2|Google Chrome)$" space=1
yabai -m rule --add app="^(Telegram|Discord)$" space=2

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

echo "yabai configuration loaded."

# Must be at the end of the file
YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &
