[buildPlans.eversevka]
family = "eversevka"
spacing = "term"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true

[buildPlans.eversevka.ligations]
inherits = "dlig"
enables = [ "center-ops" ]

[buildPlans.eversevka.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.eversevka.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.eversevka.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.eversevka.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.eversevka.weights.extrabold]
shape = 800
menu = 800
css = 800

[buildPlans.eversevka.weights.heavy]
shape = 900
menu = 900
css = 900

[buildPlans.eversevka.widths.normal]
shape = 600
menu = 5
css = "normal"
