#!/usr/bin/env sh

NORD_FROST_3=0xff81a1c1
NORD_POLAR_NIGHT_2=0xff3b4252

options=(
  width=8.0
  style=round
  active_color=$NORD_FROST_3
  inactive_color=$NORD_POLAR_NIGHT_2
)

borders "${options[@]}"
