#!/usr/bin/env sh

fn - h : \
  yabai -m query --spaces --display \
  | jq -re '(.[] as $arr | .[] | select(.index == ($arr | select(."has-focus" == true).index - 1))."first-window") // (last | ."first-window")' \
  | xargs yabai -m window --focus
fn - j : yabai -m window --focus next || yabai -m window --focus first
fn - k : yabai -m window --focus stack.next || yabai -m window --focus stack.first
fn - l : \
  yabai -m query --spaces --display \
  | jq -re '(.[] as $arr | .[] | select(.index == ($arr | select(."has-focus" == true).index + 1))."first-window") // (first | ."first-window")' \
  | xargs yabai -m window --focus

fn + cmd - h : yabai -m window --swap west
fn + cmd - j : yabai -m window --swap south
fn + cmd - k : yabai -m window --swap north
fn + cmd - l : yabai -m window --swap east

fn + alt - h : yabai -m window --warp west
fn + alt - j : yabai -m window --warp south
fn + alt - k : yabai -m window --warp north
fn + alt - l : yabai -m window --warp east

fn + ctrl - h : yabai -m window --stack west
fn + ctrl - j : yabai -m window --stack south
fn + ctrl - k : yabai -m window --stack north
fn + ctrl - l : yabai -m window --stack east

fn + shift - h : \
  yabai -m window --resize left:-20:0; \
  yabai -m window --resize right:-20:0
fn + shift - j : \
  yabai -m window --resize bottom:0:20; \
  yabai -m window --resize top:0:20
fn + shift - k : \
  yabai -m window --resize top:0:-20; \
  yabai -m window --resize bottom:0:-20
fn + shift - l : \
  yabai -m window --resize right:20:0; \
  yabai -m window --resize left:20:0

fn - q : yabai -m window --close
fn - s : yabai -m window --toggle split
fn - f : \
  yabai -m window --toggle zoom-fullscreen \
  && yabai -m window --toggle border \
  && yabai -m space --toggle padding \
  && yabai -m space --toggle gap

fn - n : yabai -m window --space next
fn - p : yabai -m window --space prev

fn - x : yabai -m space --mirror x-axis
fn - y : yabai -m space --mirror y-axis

fn - r : yabai -m space --rotate 270
fn + shift - r : yabai -m space --rotate 90

fn - b : yabai -m window --toggle border
fn - g : yabai -m space --toggle gap && yabai -m space --toggle padding

fn + shift - b : yabai -m space --balance
fn + shift - f : yabai -m window --toggle native-fullscreen
fn + shift - q : brew services restart yabai && brew services restart skhd

fn - o : open ~/
fn - i : open -a iTerm
fn - d : open -a Discord
fn - t : open -a Telegram

fn + shift - o : open -n ~/
fn + shift - i : open -na iTerm
fn + shift - c : open -na Google\ Chrome
fn + shift - d : open -na Discord
fn + shift - t : opne -na Telegram

:: default : yabai -m config active_window_border_color 0xFFA3BE8C
:: mode_chrome : yabai -m config active_window_border_color 0xFFEBCB8B

default < fn - 1 ; mode_chrome
mode_chrome < fn - c ; default
mode_chrome < fn - j ; default
mode_chrome < escape ; default

default < fn - c [
  "Google Chrome" : skhd -k "fn - 1"
  * : open -a Google\ Chrome
]

mode_chrome < j [
  "Google Chrome" : skhd -k "down"
]

mode_chrome < k [
  "Google Chrome" : skhd -k "up"
]

mode_chrome < l [
  "Google Chrome" : skhd -k "ctrl - tab"
]

mode_chrome < h [
  "Google Chrome" : skhd -k "ctrl + shift - tab"
]

mode_chrome < shift - l [
  "Google Chrome" : skhd -k "ctrl + shift - pagedown"
]

mode_chrome < shift - h [
  "Google Chrome" : skhd -k "ctrl + shift - pageup"
]
