#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh"

PADDING=4
PADDING_LABEL=8

FONT_LABEL="eversevka:bold:16.0"
FONT_FAMILY_ICON="Hack Nerd Font:Bold"
FONT_ICON="${FONT_FAMILY_ICON}:16.0"
COLOR_BAR=$NORD_POLAR_NIGHT_2
COLOR_ICON=$NORD_SNOW_STORM_1
COLOR_ICON_KEYLAYOUT=$NORD_AURORA_3
COLOR_ICON_MODE=$NORD_AURORA_3
COLOR_ICON_HIGHLIGHT=$NORD_AURORA_4
COLOR_ICON_BATTERY_LOW=$NORD_AURORA_1
COLOR_ICON_BATTERY_CHARGE=$NORD_AURORA_4
COLOR_LABEL=$NORD_SNOW_STORM_1
COLOR_BACKGROUND=$NORD_SNOW_STORM_4

COLOR_LABEL_PLAYER_OFF=$NORD_POLAR_NIGHT_4
COLOR_LABEL_PLAYER_ON=$NORD_SNOW_STORM_1
MAX_CHAR_LENGTH_PLAYER=35

COLOR_BREW_CRITICAL=$NORD_AURORA_1
COLOR_BREW_DANGER=$NORD_AURORA_2
COLOR_BREW_FINE=$NORD_AURORA_3
COLOR_BREW_LOW=$NORD_AURORA_5
COLOR_BREW_ZERO=$COLOR_ICON
