#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/properties.sh"

SCRIPTS=$HOME/.config/sketchybar/scripts

bar=(
  height=33
  shadow=off
  sticky=on
  y_offset=0
  position=top
  notch_width=200
  padding_left=$PADDING
  padding_right=$PADDING
  corner_radius=100
  color=$COLOR_BAR
)

defaults=(
  icon.font=$FONT_ICON
  icon.color=$COLOR_ICON
  icon.padding_left=$PADDING
  icon.padding_right=$PADDING
  label.font=$FONT_LABEL
  label.color=$COLOR_LABEL
  label.padding_left=$PADDING_LABEL
  label.padding_right=$PADDING_LABEL
  background.height=33
  background.corner_radius=4
  background.color=$COLOR_BACKGROUND
  updates=when_shown
)

apps=(
  updates=on
  script="$SCRIPTS/windows/windows.sh"
  drawing=off
)

brew=(
  script="$SCRIPTS/brew.sh"
  y_offset=1
  update_freq=3600
  icon=$ICON_BREW
  label.drawing=off
)

keyboard=(
  script="$SCRIPTS/keyboard.sh"
  y_offset=1
  icon.color=$COLOR_ICON_KEYBOARD
  icon=$ICON_KEYBOARD
  icon.drawing=off
  label.drawing=off
)

mode=(
  icon=":google_chrome:"
  icon.color=$COLOR_ICON_MODE
  label.drawing=off
  drawing=off
)

wake=(
  updates=on
  script="$SCRIPTS/wake.sh"
  drawing=off
)

clock=(
  update_freq=30
  script="$SCRIPTS/clock.sh"
  icon.drawing=off
)

sketchybar --hotload                   on                                                          \
           --bar                       "${bar[@]}"                                                 \
           --default                   "${defaults[@]}"                                            \
                                                                                                   \
           --add       item            apps left                                                   \
           --set       apps            "${apps[@]}"                                                \
           --add       event           window_focused                                              \
           --add       event           window_stacked                                              \
           --subscribe apps            space_windows_change                                        \
                                       front_app_switched                                          \
                                       window_focused                                              \
                                       window_stacked                                              \
                                                                                                   \
           --add       item            clock right                                                 \
           --set       clock           "${clock[@]}"                                               \
           --subscribe clock           system_woke                                                 \
                                                                                                   \
           --add       item            brew right                                                  \
           --set       brew            "${brew[@]}"                                                \
           --add       event           brew_update                                                 \
           --subscribe brew            brew_update                                                 \
                                                                                                   \
           --add       item            keyboard right                                              \
           --set       keyboard        "${keyboard[@]}"                                            \
           --add       event           input_change "AppleSelectedInputSourcesChangedNotification" \
           --subscribe keyboard        input_change                                                \
                                                                                                   \
           --add       item            mode right                                                  \
           --set       mode            "${mode[@]}"                                                \
                                                                                                   \
           --add       item            wake left                                                   \
           --set       wake            "${wake[@]}"                                                \
           --add       event           lock   "com.apple.screenIsLocked"                           \
           --add       event           unlock "com.apple.screenIsUnlocked"                         \
           --subscribe wake            lock unlock

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update
echo "sketchybar configuation loaded.."
