#!/bin/bash

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/properties.sh"
source "$HOME/.config/sketchybar/scripts/icons.sh"

SCRIPTS=$HOME/.config/sketchybar/scripts

bar=(
  height=33
  shadow=off
  sticky=on
  y_offset=0
  position=top
  notch_width=200
  padding_left=$PADDING
  padding_right=$PADDING
  corner_radius=100
  color=$COLOR_BAR
)

defaults=(
  y_offset=1
  icon.font="$FONT_ICON"
  icon.color=$COLOR_ICON
  icon.padding_left=$PADDING
  icon.padding_right=$PADDING
  label.font="$FONT_LABEL"
  label.color=$COLOR_LABEL
  label.padding_left=$PADDING_LABEL
  label.padding_right=$PADDING_LABEL
  background.height=23
  background.corner_radius=4
  background.color=$COLOR_BACKGROUND
  updates=when_shown
)

apps=(
  updates=on
  script="$SCRIPTS/windows.sh"
  drawing=off
)

__icon_map "Brew"

brew=(
  update_freq=3600
  script="$SCRIPTS/brew.sh"
  background.color=$COLOR_ICON_BACKGROUND
  background.padding_right=$PADDING
  icon.font="${FONT_FAMILY_ICON}:21.0"
  icon=$icon_result
  label.drawing=off
  drawing=off
)

__icon_map "Keylayout"

keylayout=(
  script="$SCRIPTS/keylayout.sh"
  background.color=$COLOR_ICON_BACKGROUND
  background.padding_right=$PADDING
  icon.font="${FONT_FAMILY_ICON}:21.0"
  icon.color=$COLOR_ICON_KEYLAYOUT
  icon=$icon_result
  icon.drawing=off
  label.drawing=off
)

__icon_map "Google Chrome"

mode=(
  icon=$icon_result
  icon.color=$COLOR_ICON_MODE
  background.color=$COLOR_ICON_BACKGROUND
  background.padding_right=$PADDING
  label.drawing=off
  drawing=off
)

__icon_map "Battery"

battery=(
  icon=$icon_result
  script="$SCRIPTS/battery.sh"
  background.color=$COLOR_ICON_BACKGROUND
  background.padding_right=$PADDING
  label.drawing=off
  update_freq=300
  drawing=off
)

spotify=(
  script="$SCRIPTS/spotify.sh"
  label.padding_left=$PADDING
  label.drawing=off
  icon.drawing=off
)

wake=(
  updates=on
  script="$SCRIPTS/wake.sh"
  drawing=off
)

clock=(
  update_freq=30
  script="$SCRIPTS/clock.sh"
  background.color=$COLOR_ICON_BACKGROUND
  label.color=$COLOR_ICON_HIGHLIGHT
  icon.drawing=off
)

sketchybar --hotload                   on                                                          \
           --bar                       "${bar[@]}"                                                 \
           --default                   "${defaults[@]}"                                            \
                                                                                                   \
           --add       item            apps left                                                   \
           --set       apps            "${apps[@]}"                                                \
           --add       event           window_focused                                              \
           --add       event           window_stacked                                              \
           --subscribe apps            space_windows_change                                        \
                                       front_app_switched                                          \
                                       window_focused                                              \
                                       window_stacked                                              \
                                                                                                   \
           --add       item            clock right                                                 \
           --set       clock           "${clock[@]}"                                               \
           --subscribe clock           system_woke                                                 \
                                                                                                   \
           --add       item            mode right                                                  \
           --set       mode            "${mode[@]}"                                                \
                                                                                                   \
           --add       item            brew right                                                  \
           --set       brew            "${brew[@]}"                                                \
           --add       event           brew_update                                                 \
           --subscribe brew            brew_update                                                 \
                                                                                                   \
           --add       item            battery right                                               \
           --set       battery         "${battery[@]}"                                             \
           --subscribe battery         power_source_change                                         \
                                       system_woke                                                 \
                                                                                                   \
           --add       item            keylayout right                                             \
           --set       keylayout       "${keylayout[@]}"                                           \
           --add       event           input_change "AppleSelectedInputSourcesChangedNotification" \
           --subscribe keylayout       input_change                                                \
                                                                                                   \
           --add       item            spotify e                                                   \
           --set       spotify         "${spotify[@]}"                                             \
           --add       event           spotify_change "com.spotify.client.PlaybackStateChanged"    \
           --subscribe spotify         spotify_change                                              \
                                       mouse.clicked                                               \
                                                                                                   \
           --add       item            wake left                                                   \
           --set       wake            "${wake[@]}"                                                \
           --add       event           lock   "com.apple.screenIsLocked"                           \
           --add       event           unlock "com.apple.screenIsUnlocked"                         \
           --subscribe wake            lock unlock

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update
echo "sketchybar configuation loaded.."
