#!/usr/bin/env sh

yabai -m config layout                      bsp          \
                active_window_opacity       1.0          \
                normal_window_opacity       0.95         \
                window_animation_duration   0.2          \
                window_shadow               float        \
                window_opacity              on           \
                window_opacity_duration     0.15         \
                window_gap                  5            \
                external_bar                all:33:0     \
                top_padding                 4            \
                bottom_padding              4            \
                left_padding                4            \
                right_padding               4            \
                auto_balance                off          \
                split_ratio 0.5                          \
                --space 2 split_ratio 0.6

yabai -m rule --add app="^(Системные настройки|Finder|Hiddify|App Store|VLC media player)$" manage=off
yabai -m rule --add app="^(kitty|Google Chrome)$" space=1
yabai -m rule --add app="^(Telegram|Discord)$" space=2
yabai -m rule --add app="^(Spotify)$" space=3

echo "yabai configuration loaded."
